---
- name: {{cookiecutter.project_name}}
  hosts: {{cookiecutter.server_group}}

  #roles:
  #  - role: test_role

  tasks:
  - name: Update apt
    apt:
      update_cache: true
      cache_valid_time: 3600
