---
- name: {{cookiecutter.project_name}}
  hosts: {{cookiecutter.server_group}}
  become: true
  #roles:
  #  - role: test_role

  tasks:
  - name: Install Base apt packages
    apt:
      update_cache: true
      cache_valid_time: 3600
      name: "{{ "{{" }} item {{ "}}" }}"
    with_items:
      - python-pip
      - postfix
      - mutt
