# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.provider "virtualbox" do |v|
  v.customize ["modifyvm", :id, "--cpus", "{{ cookiecutter.cpus }}", "--memory", "{{ cookiecutter.memory }}"]
end
  config.vm.define "{{ cookiecutter.box_name }}" do |{{ cookiecutter.box_name }}|
    {{ cookiecutter.box_name }}.vm.network "private_network", ip: "192.168.50.10"
    {{ cookiecutter.box_name }}.vm.hostname = "{{ cookiecutter.box_hostname }}"
    {{ cookiecutter.box_name }}.vm.box = "trusty64"
    {{ cookiecutter.box_name }}.vm.box_url = "http://files.vagrantup.com/trusty64.box"
  end


  # -------- Enable provisioning with Ansible.  --------
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
    # Uncomment below to see debug output.
    #ansible.verbose = 'vvv'
    ansible.groups = {
        "{{ cookiecutter.server_group }}" => ["{{ cookiecutter.box_name }}"]
    }
  end
end
